/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x97, 0xD0, 0xA5, 0x97, 0x57, 0x48, 0xD0, 0x4F}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#ifndef FLOW_TAP_TERM
#    define FLOW_TAP_TERM 150
#endif

#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#ifndef PERMISSIVE_HOLD_PER_KEY
#    define PERMISSIVE_HOLD_PER_KEY
#endif

#define SPLIT_TRANSACTION_IDS_USER RPC_ID_USER_KEYPRESS_LED

#define RGBLIGHT_LED_COUNT 2
#define RGBLED_SPLIT { 1, 1 }
#define WS2812_DI_PIN GP16
#define RGBLIGHT_LAYERS

#ifndef SILAKKA54_KEYPRESS_LED_FEEDBACK
#    define SILAKKA54_KEYPRESS_LED_FEEDBACK 1
#endif

#ifndef SILAKKA54_LAYER_LED_INTENSITY
#    define SILAKKA54_LAYER_LED_INTENSITY 0.31372549
#endif

#ifndef SILAKKA54_KEYPRESS_LED_INTENSITY
#    define SILAKKA54_KEYPRESS_LED_INTENSITY 0.25
#endif

#ifndef SILAKKA54_CAPS_LED_INTENSITY
#    define SILAKKA54_CAPS_LED_INTENSITY 0.39215686
#endif
